pipelines:
  branches:
    production:
    - step:
        caches:
        - composer
        name: Build PHP part
        image: ogorbunov/php:7.2-deploy
        script:
        - echo "Starting php build"
        - export COMPOSER_ALLOW_SUPERUSER=1
        - composer install --ignore-platform-reqs --no-suggest --no-progress
        - composer du
        artifacts:
        - vendor/**

    - step:
        caches:
        - node
        name: Build Laravel Mix
        image: node:10.9
        script:
        - echo "Starting mix build"
        - npm install
        - npm run prod
        artifacts:
        - public/assets/app.css
        - public/assets/app.js
        - public/fonts/*
        - public/mix-manifest.json

    - step:
        name: Deploying to server
        image: ogorbunov/php:7.2-deploy
        deployment: staging
        script:
        - echo "Deployment started"
        - dep deploy dechees.devpoint.kz
