version: "3.7"

services:
  app-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: dchs-app-nginx:v2
    # container_name: "app-nginx"
    ports:
      - 3080:80
    networks:
      - app-network
    depends_on:
      - app-fpm

  app-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: dchs-app-fpm:v2
    # container_name: "app-fpm"
    working_dir: /var/www
    networks:
      - app-network
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL}
      APP_SCHEME: ${APP_SCHEME:-http}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-app-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-redis}
      REDIS_HOST: ${REDIS_HOST:-app-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-http://app-elasticsearch}
    tty: true
    expose:
      - "9000"
      - "9001"

  app-db:
    image: mysql:8.0
    # container_name: "app-db"
    ports:
      - 33306:3306
    volumes:
      - ./database/dumps/report_cache_structure.sql:/docker-entrypoint-initdb.d/02-report-cache-structure.sql:ro
      - app-db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_HOST: "%"
    command:
      - "--log_bin_trust_function_creators=1"

  app-queue:
    # container_name: "app-queue"
    image: dchs-app-fpm:v2
    networks:
      - app-network
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL}
      APP_SCHEME: ${APP_SCHEME:-http}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-app-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-redis}
      REDIS_HOST: ${REDIS_HOST:-app-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    command: php /var/www/artisan queue:work
    restart: unless-stopped

  app-redis:
    # container_name: "app-redis"
    image: redis:latest
    networks:
      - app-network

  app-broadcast:
    # container_name: "app-broadcast"
    image: node:10
    networks:
      - app-network
    volumes:
      - ./echo-server:/app
    ports:
      - 6001:6001
    working_dir: /app
    command: sh ./start.sh
    restart: unless-stopped

  #  app-elasticsearch:
  #    container_name: "app-elasticsearch"
  #    image: elasticsearch:5.6
  #    networks:
  #      - app-network

#  app-scout-models:
#    container_name: "app-scout-models"
#    image: ogorbunov/php:7.3-cli-alpine
#    volumes:
#      - ./:/current
#    environment:
#      APP_ENV: local
#      APP_DEBUG: 1
#      APP_KEY: "base64:46UPFHEBEGaa9CBU4SQbNd5N0BZAxW5gmDB0e12kcRk="
#      DB_CONNECTION: mysql
#      DB_HOST: app-db
#      DB_PORT: 3306
#      DB_USERNAME: emergency
#      DB_PASSWORD: emergency
#      DB_DATABASE: emergency
#      ELASTICSEARCH_HOST: http://app-elasticsearch
#    command: /current/.docker/scouting.sh
#    networks:
#      - app-network
#    depends_on:
#      - app-composer-vendors
#      - app-elasticsearch
#      - app-db

volumes:
  app-db-data:
  app-code:


networks:
  app-network:
