version: "3.3"

services:
  app-nginx:
    image: nginx:alpine
    container_name: "app-nginx"
    ports:
      - "3080:80"
    volumes:
      - ./:/current
      - ./_docker/routing/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./_docker/routing/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./_docker/routing/conf.d/:/etc/nginx/conf.d:ro
    networks:
      - app-network

  app-fpm:
    image: ogorbunov/php:7.2-fpm-mysql
    container_name: "app-fpm"
    volumes:
      - ./:/current
      - ./_docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./_docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    networks:
      - app-network
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: "base64:46UPFHEBEGaa9CBU4SQbNd5N0BZAxW5gmDB0e12kcRk="
      DB_CONNECTION: mysql
      DB_HOST: app-db
      DB_PORT: 3306
      DB_USERNAME: emergency
      DB_PASSWORD: emergency
      DB_DATABASE: emergency
      BROADCAST_DRIVER: redis
      REDIS_HOST: app-redis
      REDIS_PORT: 6379

  app-db:
    image: mysql:5.7
    container_name: "app-db"
    ports:
      - "33306:3306"
    volumes:
      - ./database/dumps/emergency-20-03-2019.sql.gz:/docker-entrypoint-initdb.d/01-init.sql.gz
      - ./database/dumps/report_cache_structure.sql:/docker-entrypoint-initdb.d/02-report-cache-structure.sql.gz
      - app-db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_USER: emergency
      MYSQL_PASSWORD: emergency
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emergency

  app-queue:
    image: ogorbunov/php:7.2-fpm-mysql
    volumes:
      - ./:/current
    networks:
      - app-network
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: "base64:46UPFHEBEGaa9CBU4SQbNd5N0BZAxW5gmDB0e12kcRk="
      DB_CONNECTION: mysql
      DB_HOST: app-db
      DB_PORT: 3306
      DB_USERNAME: emergency
      DB_PASSWORD: emergency
      DB_DATABASE: emergency
      BROADCAST_DRIVER: redis
      REDIS_HOST: app-redis
      REDIS_PORT: 6379
    command: php /current/artisan queue:work

  app-redis:
    image: redis:latest
    networks:
      - app-network

  app-broadcast:
    image: node:10
    networks:
      - app-network
    volumes:
      - ./echo-server:/app
    ports:
      - 6001:6001
    working_dir: /app
    command: ./start.sh

volumes:
  app-db-data:
  app-code:

networks:
  app-network:
    external: true

